name: "Terraform Plan"
description: "Executes TF plan against s3 backend tf_state"
runs:
  using: "composite"
  steps: 
    - name: "Configure TF"
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: "TF INIT"
      working-directory: "./terraform/"
      shell: "bash"
      run: terraform init -reconfigure
    - name: "TF PLAN"
      working-directory: "./terraform/"
      shell: "bash"
      run: |
        ls
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        
        if [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
        else 
          exit 0
        fi

    - name: "ARCHIVE TF PLAN"
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: tfplan
