name: "tf plan"
on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "zwell-test"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "dev-test"
  CONFIG_DIRECTORY: "./"
jobs:
  terraform:
    name: "tf plan devtest"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "plan"
        uses: ./.github/terraform/plan.yml
      