name: "tf plan"
on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "zwell-test"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "dev-test"
  CONFIG_DIRECTORY: "./"
jobs:
  terraform:
    name: "tf plan devtest"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Configure TF"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: "TF INIT"
        working-directory: "./terraform/"
        shell: "bash"
        run: |
          echo "${TF_API_TOKEN}"
          terraform init -reconfigure
      - name: "TF PLAN"
        working-directory: "./terraform/"
        shell: "bash"
        run: |
          
          export exitcode=0
          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
  
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          
          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else 
            exit 0
          fi
  
      - name: "ARCHIVE TF PLAN"
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
      